// Code generated by protoc-gen-go.
// source: packet.proto
// DO NOT EDIT!

/*
Package packet is a generated protocol buffer package.

It is generated from these files:
	packet.proto

It has these top-level messages:
	Packet
*/
package packet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import schema "github.com/dallasmccall/goplay/proto/schema"
import dataset "github.com/dallasmccall/goplay/proto/dataset"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Packet struct {
	Schema []*schema.Schema   `protobuf:"bytes,1,rep,name=schema" json:"schema,omitempty"`
	Data   []*dataset.DataSet `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
}

func (m *Packet) Reset()                    { *m = Packet{} }
func (m *Packet) String() string            { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()               {}
func (*Packet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Packet) GetSchema() []*schema.Schema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *Packet) GetData() []*dataset.DataSet {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Packet)(nil), "Packet")
}

func init() { proto.RegisterFile("packet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x4c, 0xce,
	0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x12, 0x2e, 0x4e, 0xce, 0x48, 0xcd, 0x4d,
	0xd4, 0x87, 0x50, 0x50, 0x41, 0xd1, 0x94, 0xc4, 0x92, 0xc4, 0xe2, 0xd4, 0x12, 0x7d, 0x28, 0x0d,
	0x11, 0x56, 0x72, 0xe7, 0x62, 0x0b, 0x00, 0xeb, 0x15, 0x92, 0xe7, 0x62, 0x83, 0x68, 0x90, 0x60,
	0x54, 0x60, 0xd6, 0xe0, 0x36, 0x62, 0xd7, 0x0b, 0x06, 0x73, 0x83, 0xa0, 0xc2, 0x42, 0x32, 0x5c,
	0x2c, 0x20, 0xbd, 0x12, 0x4c, 0x60, 0x69, 0x0e, 0x3d, 0x97, 0xc4, 0x92, 0xc4, 0xe0, 0xd4, 0x92,
	0x20, 0xb0, 0x68, 0x12, 0x1b, 0xd8, 0x3c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x49,
	0x25, 0x19, 0x8b, 0x00, 0x00, 0x00,
}
